backend:
  name: git-gateway
  branch: main

# Change url to a link to the image you want to use, no file paths, must be a URL
logo:
  src: "https://padreza.netlify.app/assets/svgs/Padreza_logo.svg"
  show_in_header: false

locale: "cs"
media_folder: "src/assets/images/cms"
public_folder: "/assets/images/cms"
local_backend: true

collections:
  - summary: "{{jmeno}} • {{mnozstvi}} • {{drevo}} • {{suchost}} • {{delka}} [{{date}}]"
    sortable_fields: ["date", "jmeno", "status"]
    view_filters:
      - label: "nová poptávka"
        field: status
        pattern: "nová poptávka"
      - label: "zákazník kontaktován"
        field: status
        pattern: "zákazník kontaktován"
      - label: "vyřízeno"
        field: status
        pattern: "vyřízeno"
    name: "poptavky"
    label: "Poptávky"
    folder: "src/content/i18n/cs/poptavky"
    create: false # formulář generuje soubory, CMS je pouze pro úpravu
    delete: true
    editor:
      preview: true
    fields:
      - {
          label: "Datum",
          name: "date",
          widget: "datetime",
          required: true,
          readonly: true,
        }
      - {
          label: "Stav",
          name: "status",
          widget: "select",
          options: ["nová poptávka", "zákazník kontaktován", "vyřízeno"],
        }
      - { label: "Jméno", name: "jmeno", widget: "string", readonly: true }
      - { label: "Telefon", name: "telefon", widget: "string", readonly: true }
      - { label: "E-mail", name: "mail", widget: "string", readonly: true }
      - {
          label: "Délka",
          name: "delka",
          widget: "select",
          options: ["25 cm", "33 cm", "40 cm", "50 cm"],
          readonly: true,
        }
      - {
          label: "Dřevo",
          name: "drevo",
          widget: "select",
          options: ["měkké", "polotvrdé", "tvrdé"],
          readonly: true,
        }
      - {
          label: "Suchost",
          name: "suchost",
          widget: "select",
          options: ["suché", "čerstvé"],
          readonly: true,
        }
      - {
          label: "Doprava",
          name: "doprava",
          widget: "select",
          options: ["vlastní", "smluvní dopravce"],
          readonly: true,
        }
      - {
          label: "Adresa",
          name: "adresa",
          widget: "string",
          readonly: true,
          required: false,
        }
      - {
          label: "Množství prms",
          name: "mnozstvi",
          widget: "string",
          readonly: true,
        }
      - {
          label: "Poznámka",
          name: "poznamka",
          widget: "text",
          readonly: true,
          required: false,
        }
      - { label: "Komentář", name: "komentar", widget: "text", required: false }
