# prettier-ignore
# Use DecapBridge classic auth (required)
backend:
  name: decap-bridge
  repo: coalmarketing/padreza
  branch: main
  identity_url: https://auth.decapbridge.com/sites/038b665b-a7fe-4f33-85bc-87c887c87c47
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} â€œ{{slug}}â€ - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} â€œ{{slug}}â€ - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} â€œ{{slug}}â€ - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload â€œ{{path}}â€ - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete â€œ{{path}}â€ - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Add site links in Decap CMS (optional)
site_url: https://padreza.netlify.app

# Change url to a link to the image you want to use, no file paths, must be a URL
logo:
  src: "https://padreza.netlify.app/assets/svgs/Padreza_logo.svg"
  show_in_header: false

locale: "cs"
media_folder: "" # Å¾Ã¡dnÃ¡ sloÅ¾ka pro soubory
public_folder: "" # Å¾Ã¡dnÃ¡ cesta pro veÅ™ejnÃ© odkazy
local_backend: false

collections:
  # =========================
  # KONTAKTY
  # =========================
  - name: "kontakty"
    label: "1 - Kontakty"
    summary: "ğŸ‘¤ {{jmeno}} ğŸ“® {{mail}} ğŸ“ {{telefon}} ğŸ—“ï¸ {{datum}} â° {{cas}}"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: "kontakt"
    sortable_fields: ["date", "jmeno"]
    editor:
      preview: true
    fields:
      - {
          label: "Stav",
          name: "status",
          widget: "select",
          options:
            ["kontakt", "novÃ¡ poptÃ¡vka", "zÃ¡kaznÃ­k kontaktovÃ¡n", "vyÅ™Ã­zeno"],
        }
      - { label: "JmÃ©no", name: "jmeno", widget: "string", required: true }
      - { label: "Telefon", name: "telefon", widget: "string", required: true }
      - { label: "E-mail", name: "mail", widget: "string", required: true }
      - { label: "PoznÃ¡mka", name: "poznamka", widget: "text", required: false }

  # =========================
  # NOVÃ‰ POPTÃVKY
  # =========================
  - name: "poptavky_nove"
    label: "2 - PoptÃ¡vky"
    summary: "ğŸ—“ï¸ {{datum}} ğŸ‘¤ {{jmeno}} ğŸªµ {{mnozstvi}} prms - {{suchost}} {{drevo}} ğŸšš {{doprava}}"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: "novÃ¡ poptÃ¡vka"
    sortable_fields: ["date", "jmeno"]
    editor:
      preview: true
    fields: &poptavky_fields
      - {
          label: "Stav",
          name: "status",
          widget: "select",
          options:
            ["kontakt", "novÃ¡ poptÃ¡vka", "zÃ¡kaznÃ­k kontaktovÃ¡n", "vyÅ™Ã­zeno"],
        }
      - { label: "JmÃ©no", name: "jmeno", widget: "string", required: true }
      - { label: "Telefon", name: "telefon", widget: "string", required: true }
      - { label: "E-mail", name: "mail", widget: "string", required: true }
      - {
          label: "DÃ©lka",
          name: "delka",
          widget: "select",
          options: ["25 cm", "33 cm", "40 cm", "50 cm"],
          required: false,
        }
      - {
          label: "DÅ™evo",
          name: "drevo",
          widget: "select",
          options: ["mÄ›kkÃ©", "polotvrdÃ©", "tvrdÃ©"],
          required: false,
        }
      - {
          label: "Suchost",
          name: "suchost",
          widget: "select",
          options: ["suchÃ©", "ÄerstvÃ©"],
          required: false,
        }
      - {
          label: "Doprava",
          name: "doprava",
          widget: "select",
          options: ["vlastnÃ­", "smluvnÃ­ dopravce"],
          required: false,
        }
      - { label: "Adresa", name: "adresa", widget: "string", required: false }
      - {
          label: "MnoÅ¾stvÃ­ (prms)",
          name: "mnozstvi",
          widget: "string",
          required: false,
        }
      - { label: "PoznÃ¡mka", name: "poznamka", widget: "text", required: false }

  # =========================
  # KONTAKTOVANÃ‰
  # =========================
  - name: "poptavky_kontaktovane"
    label: "3 - V Å™eÅ¡enÃ­ (kontaktovÃ¡no)"
    summary: "ğŸ—“ï¸ {{datum}} ğŸ‘¤ {{jmeno}} ğŸªµ {{mnozstvi}} prms - {{suchost}} {{drevo}} ğŸšš {{doprava}}"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: "zÃ¡kaznÃ­k kontaktovÃ¡n"
    sortable_fields: ["date", "jmeno"]
    editor:
      preview: true
    fields: *poptavky_fields

  # =========================
  # VYÅ˜ÃZENÃ‰
  # =========================
  - name: "poptavky_vyrizene"
    label: "4 - VyÅ™Ã­zenÃ©"
    summary: "ğŸ—“ï¸ {{datum}} ğŸ‘¤ {{jmeno}} ğŸªµ {{mnozstvi}} prms - {{suchost}} {{drevo}} ğŸšš {{doprava}}"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: "vyÅ™Ã­zeno"
    sortable_fields: ["date", "jmeno"]
    editor:
      preview: true
    fields: *poptavky_fields
