backend:
  name: git-gateway
  branch: main
  # aktivní Git Gateway
  # pokud používáš lokální backend, můžeš přidat: local_backend: true

local_backend: true

# Logo v headeru skryto
logo:
  # src: "https://www.senoweb.cz/assets/images/senoweb_og_logo_rounded.png"
  show_in_header: false

locale: "cs"

# Media Library deaktivovaná
media_folder: "src/assets/images/cms"
public_folder: "/assets/images/cms"
media_library:
  name: "disabled"

# Pouze kolekce poptávek
collections:
  - name: "poptavky"
    label: "Poptávky"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    editor:
      preview: false
    fields:
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Délka", name: "Delka", widget: "string" }
      - { label: "Dřevo", name: "Drevo", widget: "string" }
      - { label: "Suchost", name: "Suchost", widget: "string" }
      - { label: "Doprava", name: "Doprava", widget: "string" }
      - { label: "Adresa", name: "Adresa", widget: "string" }
      - { label: "Množství", name: "Mnozstvi", widget: "string" }
      - { label: "Poznámka", name: "Poznamka", widget: "text", required: false }
      - {
          label: "Stav",
          name: "status",
          widget: "select",
          options: ["nová poptávka", "zákazník kontaktován", "vyřízeno"],
        }
