# prettier-ignore
backend:
  name: git-gateway
  branch: main

# Change url to a link to the image you want to use, no file paths, must be a URL
logo:
  src: "https://padreza.netlify.app/assets/svgs/Padreza_logo.svg"
  show_in_header: false

locale: "cs"
media_folder: "src/assets/images/cms"
public_folder: "/assets/images/cms"
local_backend: true

collections:
  # =========================
  # KONTAKTY
  # =========================
  - name: "kontakty"
    label: "1. Kontakty"
    summary: "ğŸ‘¤ {{jmeno}} ğŸ“® {{mail}} ğŸ“ {{telefon}} ğŸ—“ï¸ {{datum}} â° {{cas}}"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: "kontakt"
    sortable_fields: ["datum", "jmeno"]
    editor:
      preview: true
    fields:
      - {
          label: "Stav",
          name: "status",
          widget: "select",
          options:
            ["kontakt", "novÃ¡ poptÃ¡vka", "zÃ¡kaznÃ­k kontaktovÃ¡n", "vyÅ™Ã­zeno"],
        }
      - { label: "JmÃ©no", name: "jmeno", widget: "string", readonly: true }
      - { label: "Telefon", name: "telefon", widget: "string", readonly: true }
      - { label: "E-mail", name: "mail", widget: "string", readonly: true }
      - { label: "KomentÃ¡Å™", name: "komentar", widget: "text", required: false}

  # =========================
  # NOVÃ‰ POPTÃVKY
  # =========================
  - name: "poptavky_nove"
    label: "2. PoptÃ¡vky"
    summary: "ğŸ—“ï¸ {{datum}} ğŸ‘¤ {{jmeno}} ğŸªµ {{suchost}} {{drevo}} / {{mnozstvi}} prms ğŸšš {{doprava}}"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: "novÃ¡ poptÃ¡vka"
    sortable_fields: ["date", "jmeno"]
    editor:
      preview: true
    fields: &poptavky_fields
      - {
          label: "Stav",
          name: "status",
          widget: "select",
          options:
            ["kontakt", "novÃ¡ poptÃ¡vka", "zÃ¡kaznÃ­k kontaktovÃ¡n", "vyÅ™Ã­zeno"],
        }
      - { label: "JmÃ©no", name: "jmeno", widget: "string", readonly: true }
      - { label: "Telefon", name: "telefon", widget: "string", readonly: true }
      - { label: "E-mail", name: "mail", widget: "string", readonly: true }
      - {
          label: "DÃ©lka",
          name: "delka",
          widget: "select",
          options: ["25 cm", "33 cm", "40 cm", "50 cm"],
          readonly: true,
        }
      - {
          label: "DÅ™evo",
          name: "drevo",
          widget: "select",
          options: ["mÄ›kkÃ©", "polotvrdÃ©", "tvrdÃ©"],
          readonly: true,
        }
      - {
          label: "Suchost",
          name: "suchost",
          widget: "select",
          options: ["suchÃ©", "ÄerstvÃ©"],
          readonly: true,
        }
      - {
          label: "Doprava",
          name: "doprava",
          widget: "select",
          options: ["vlastnÃ­", "smluvnÃ­ dopravce"],
          readonly: true,
        }
      - {
          label: "Adresa",
          name: "adresa",
          widget: "string",
          readonly: true,
          required: false,
        }
      - {
          label: "MnoÅ¾stvÃ­ (prms)",
          name: "mnozstvi",
          widget: "string",
          readonly: true,
        }
      - {
          label: "PoznÃ¡mka",
          name: "poznamka",
          widget: "text",
          readonly: true,
          required: false,
        }
      - { label: "KomentÃ¡Å™", name: "komentar", widget: "text", required: false}

  # =========================
  # KONTAKTOVANÃ‰
  # =========================
  - name: "poptavky_kontaktovane"
    label: "3. V Å™eÅ¡enÃ­ (kontaktovÃ¡no)"
    summary: "ğŸ—“ï¸ {{datum}} ğŸ‘¤ {{jmeno}} ğŸªµ {{suchost}} {{drevo}} / {{mnozstvi}} ğŸšš {{doprava}}"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: "zÃ¡kaznÃ­k kontaktovÃ¡n"
    sortable_fields: ["date", "jmeno"]
    editor:
      preview: true
    fields: *poptavky_fields

  # =========================
  # VYÅ˜ÃZENÃ‰
  # =========================
  - name: "poptavky_vyrizene"
    label: "4. VyÅ™Ã­zenÃ©"
    summary: "ğŸ—“ï¸ {{datum}} ğŸ‘¤ {{jmeno}} ğŸªµ {{suchost}} {{drevo}} / {{mnozstvi}} ğŸšš {{doprava}}"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: "vyÅ™Ã­zeno"
    sortable_fields: ["date", "jmeno"]
    editor:
      preview: true
    fields: *poptavky_fields
