backend:
  name: git-gateway
  branch: main

locale: "cs"

collections:
  - name: "poptavky"
    label: "Poptávky"
    folder: "src/content/i18n/cs/poptavky"
    create: false # formulář generuje soubory, CMS je pouze pro úpravu
    delete: true
    editor:
      preview: false
    fields:
      - {
          label: "Datum",
          name: "date",
          widget: "datetime",
          required: true,
          readonly: true,
        }
      - { label: "Jméno", name: "jmeno", widget: "string", readonly: true }
      - { label: "Telefon", name: "telefon", widget: "string", readonly: true }
      - { label: "E-mail", name: "mail", widget: "string", readonly: true }
      - { label: "Délka", name: "delka", widget: "string", readonly: true }
      - { label: "Dřevo", name: "drevo", widget: "string", readonly: true }
      - { label: "Suchost", name: "suchost", widget: "string", readonly: true }
      - { label: "Doprava", name: "doprava", widget: "string", readonly: true }
      - { label: "Adresa", name: "adresa", widget: "string", readonly: true }
      - {
          label: "Množství",
          name: "mnozstvi",
          widget: "string",
          readonly: true,
        }
      - {
          label: "Poznámka",
          name: "poznamka",
          widget: "text",
          readonly: true,
          required: false,
        }
      - { label: "Komentář", name: "komentar", widget: "text", required: false }
      - {
          label: "Stav",
          name: "status",
          widget: "select",
          options: ["nová poptávka", "zákazník kontaktován", "vyřízeno"],
        }
