backend:
  name: git-gateway
  branch: main

# Change url to a link to the image you want to use, no file paths, must be a URL
logo:
  src: "https://padreza.netlify.app/assets/svgs/Padreza_logo.svg"
  show_in_header: false

locale: "cs"
media_folder: "src/assets/images/cms"
public_folder: "/assets/images/cms"
local_backend: true

collections:
  # =========================
  # NOV√â POPT√ÅVKY
  # =========================
  - name: "poptavky_nove"
    label: "Popt√°vky ‚Äì nov√©"
    summary: "{{jmeno}} ‚Ä¢ {{mnozstvi}} ‚Ä¢ {{drevo}} ‚Ä¢ {{suchost}} ‚Ä¢ {{delka}} [{{date}}]"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: "nov√° popt√°vka"
    sortable_fields: ["date", "jmeno"]
    editor:
      preview: true
    fields: &poptavky_fields
      - { label: "Datum", name: "date", widget: "datetime", readonly: true }
      - {
          label: "Stav",
          name: "status",
          widget: "select",
          options:
            [
              "nov√Ω kontakt",
              "nov√° popt√°vka",
              "z√°kazn√≠k kontaktov√°n",
              "vy≈ô√≠zeno",
            ],
        }
      - { label: "Jm√©no", name: "jmeno", widget: "string", readonly: true }
      - { label: "Telefon", name: "telefon", widget: "string", readonly: true }
      - { label: "E-mail", name: "mail", widget: "string", readonly: true }
      - {
          label: "D√©lka",
          name: "delka",
          widget: "select",
          options: ["25 cm", "33 cm", "40 cm", "50 cm"],
          readonly: true,
        }
      - {
          label: "D≈ôevo",
          name: "drevo",
          widget: "select",
          options: ["mƒõkk√©", "polotvrd√©", "tvrd√©"],
          readonly: true,
        }
      - {
          label: "Suchost",
          name: "suchost",
          widget: "select",
          options: ["such√©", "ƒçerstv√©"],
          readonly: true,
        }
      - {
          label: "Doprava",
          name: "doprava",
          widget: "select",
          options: ["vlastn√≠", "smluvn√≠ dopravce"],
          readonly: true,
        }
      - {
          label: "Adresa",
          name: "adresa",
          widget: "string",
          readonly: true,
          required: false,
        }
      - {
          label: "Mno≈æstv√≠ prms",
          name: "mnozstvi",
          widget: "string",
          readonly: true,
        }
      - {
          label: "Pozn√°mka",
          name: "poznamka",
          widget: "text",
          readonly: true,
          required: false,
        }
      - { label: "Koment√°≈ô", name: "komentar", widget: "text", required: false }

  # =========================
  # KONTAKTOVAN√â
  # =========================
  - name: "poptavky_kontaktovane"
    label: "Popt√°vky ‚Äì kontaktovan√©"
    summary: "{{jmeno}} ‚Ä¢ {{mnozstvi}} ‚Ä¢ {{drevo}} ‚Ä¢ {{delka}}"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: "z√°kazn√≠k kontaktov√°n"
    sortable_fields: ["date", "jmeno"]
    editor:
      preview: true
    fields: *poptavky_fields

  # =========================
  # VY≈ò√çZEN√â
  # =========================
  - name: "poptavky_vyrizene"
    label: "Popt√°vky ‚Äì vy≈ô√≠zen√©"
    summary: "{{jmeno}} ‚Ä¢ {{mnozstvi}} ‚Ä¢ {{drevo}}"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: "vy≈ô√≠zeno"
    sortable_fields: ["date", "jmeno"]
    editor:
      preview: true
    fields: *poptavky_fields

  # =========================
  # VY≈ò√çZEN√â
  # =========================
  - name: "kontakty"
    label: "Kontakty"
    summary: "{{jmeno}} ‚úâÔ∏è {{mail}} üìû {{telefon}} üóìÔ∏è {{datum}} ‚è∞ {{cas}}"
    folder: "src/content/i18n/cs/poptavky"
    create: false
    delete: true
    filter:
      field: status
      value: ["kontakt", "nov√Ω kontakt"]
    sortable_fields: ["date", "jmeno"]
    editor:
      preview: true
    fields: *poptavky_fields
